#!/usr/bin/env python3
#agrep

import sys
import os
from functions import re_to_nfa, read_nfa, match

def main():
    regex = list(sys.argv[1:][0])
    #print(f"regex = {regex}")

    nfa_file = re_to_nfa(regex)
    M = read_nfa(nfa_file)
    os.remove(nfa_file)

    for line in sys.stdin:
        line = line.strip()

        if line == "end":
            break

        result = match(M, line)

        if result:
            print(line)
        else:
            continue
    

    #print_file(nfa_file)

# Main Execution

if __name__ == '__main__':
    main()
