#!/usr/bin/env python3
#concat_nfa

import sys
from functions import concat_nfa, print_file

def main():
    w = list(sys.argv[1:])

    nfa_file1 = w[0]
    nfa_file2 = w[1]

    concat_nfa(nfa_file1, nfa_file2, "output_file")

    print_file("output_file")

# Main Execution

if __name__ == '__main__':
    main()
