#!/usr/bin/env python3
#re_to_nfa
import sys
from functions import re_to_nfa, print_file

def main():
    w = list(sys.argv[1:][0])
    nfa_file = re_to_nfa(w)

    print_file(nfa_file)

# Main Execution

if __name__ == '__main__':
    main()

