#!/usr/bin/env python3
#string_nfa

import sys
from functions import string_nfa, print_file

def main():
    w = list(sys.argv[1:][0])
    string_nfa(w, "output_file")

    print_file("output_file")


# Main Execution

if __name__ == '__main__':
    main()
